/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BodaccVenteAllOf model module.
 * @module model/BodaccVenteAllOf
 * @version 2.3.0
 */
class BodaccVenteAllOf {
    /**
     * Constructs a new <code>BodaccVenteAllOf</code>.
     * @alias module:model/BodaccVenteAllOf
     */
    constructor() { 
        
        BodaccVenteAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BodaccVenteAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BodaccVenteAllOf} obj Optional instance to populate.
     * @return {module:model/BodaccVenteAllOf} The populated <code>BodaccVenteAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BodaccVenteAllOf();

            if (data.hasOwnProperty('rcs')) {
                obj['rcs'] = ApiClient.convertToType(data['rcs'], 'String');
            }
            if (data.hasOwnProperty('nom_entreprise')) {
                obj['nom_entreprise'] = ApiClient.convertToType(data['nom_entreprise'], 'String');
            }
            if (data.hasOwnProperty('personne_morale')) {
                obj['personne_morale'] = ApiClient.convertToType(data['personne_morale'], 'Boolean');
            }
            if (data.hasOwnProperty('denomination')) {
                obj['denomination'] = ApiClient.convertToType(data['denomination'], 'String');
            }
            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('prenom')) {
                obj['prenom'] = ApiClient.convertToType(data['prenom'], 'String');
            }
            if (data.hasOwnProperty('administration')) {
                obj['administration'] = ApiClient.convertToType(data['administration'], 'String');
            }
            if (data.hasOwnProperty('adresse')) {
                obj['adresse'] = ApiClient.convertToType(data['adresse'], 'String');
            }
            if (data.hasOwnProperty('commentaires')) {
                obj['commentaires'] = ApiClient.convertToType(data['commentaires'], 'String');
            }
            if (data.hasOwnProperty('oppositions')) {
                obj['oppositions'] = ApiClient.convertToType(data['oppositions'], 'String');
            }
            if (data.hasOwnProperty('declaration_creance')) {
                obj['declaration_creance'] = ApiClient.convertToType(data['declaration_creance'], 'String');
            }
            if (data.hasOwnProperty('publication_legale')) {
                obj['publication_legale'] = ApiClient.convertToType(data['publication_legale'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Greffe de publication.
 * @member {String} rcs
 */
BodaccVenteAllOf.prototype['rcs'] = undefined;

/**
 * Nom de l'entreprise concernée par la publication. Correspond à la dénomination en cas de personne morale et à nom + prenom en cas de personne physique.
 * @member {String} nom_entreprise
 */
BodaccVenteAllOf.prototype['nom_entreprise'] = undefined;

/**
 * Vrai si l'entreprise concernée par la publication est une personne morale, faux si c'est une personne physique.
 * @member {Boolean} personne_morale
 */
BodaccVenteAllOf.prototype['personne_morale'] = undefined;

/**
 * Dénomination de l'entreprise concernée par la publication (uniquement en cas de personne morale).
 * @member {String} denomination
 */
BodaccVenteAllOf.prototype['denomination'] = undefined;

/**
 * Nom de la personne physique concernée par la publication (uniquement en cas de personne physique).
 * @member {String} nom
 */
BodaccVenteAllOf.prototype['nom'] = undefined;

/**
 * Prénom de la personne physique concernée par la publication (uniquement en cas de personne physique).
 * @member {String} prenom
 */
BodaccVenteAllOf.prototype['prenom'] = undefined;

/**
 * Administration (dans le cas d'une personne morale).
 * @member {String} administration
 */
BodaccVenteAllOf.prototype['administration'] = undefined;

/**
 * Adresse de l'entreprise concernée par la publication.
 * @member {String} adresse
 */
BodaccVenteAllOf.prototype['adresse'] = undefined;

/**
 * Commentaires sur la publication.
 * @member {String} commentaires
 */
BodaccVenteAllOf.prototype['commentaires'] = undefined;

/**
 * Détails sur les oppositions.
 * @member {String} oppositions
 */
BodaccVenteAllOf.prototype['oppositions'] = undefined;

/**
 * Détails sur la déclaration de créance.
 * @member {String} declaration_creance
 */
BodaccVenteAllOf.prototype['declaration_creance'] = undefined;

/**
 * Journal où a été publiée la publication légale.
 * @member {String} publication_legale
 */
BodaccVenteAllOf.prototype['publication_legale'] = undefined;






export default BodaccVenteAllOf;

