/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Bodacc from './Bodacc';
import BodaccCreationAllOf from './BodaccCreationAllOf';

/**
 * The BodaccCreation model module.
 * @module model/BodaccCreation
 * @version 2.3.0
 */
class BodaccCreation {
    /**
     * Constructs a new <code>BodaccCreation</code>.
     * @alias module:model/BodaccCreation
     * @extends module:model/Bodacc
     * @implements module:model/Bodacc
     * @implements module:model/BodaccCreationAllOf
     */
    constructor() { 
        Bodacc.initialize(this);BodaccCreationAllOf.initialize(this);
        BodaccCreation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BodaccCreation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BodaccCreation} obj Optional instance to populate.
     * @return {module:model/BodaccCreation} The populated <code>BodaccCreation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BodaccCreation();
            Bodacc.constructFromObject(data, obj);
            Bodacc.constructFromObject(data, obj);
            BodaccCreationAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('rcs')) {
                obj['rcs'] = ApiClient.convertToType(data['rcs'], 'String');
            }
            if (data.hasOwnProperty('nom_entreprise')) {
                obj['nom_entreprise'] = ApiClient.convertToType(data['nom_entreprise'], 'String');
            }
            if (data.hasOwnProperty('personne_morale')) {
                obj['personne_morale'] = ApiClient.convertToType(data['personne_morale'], 'Boolean');
            }
            if (data.hasOwnProperty('denomination')) {
                obj['denomination'] = ApiClient.convertToType(data['denomination'], 'String');
            }
            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('prenom')) {
                obj['prenom'] = ApiClient.convertToType(data['prenom'], 'String');
            }
            if (data.hasOwnProperty('administration')) {
                obj['administration'] = ApiClient.convertToType(data['administration'], 'String');
            }
            if (data.hasOwnProperty('adresse')) {
                obj['adresse'] = ApiClient.convertToType(data['adresse'], 'String');
            }
            if (data.hasOwnProperty('capital')) {
                obj['capital'] = ApiClient.convertToType(data['capital'], 'Number');
            }
            if (data.hasOwnProperty('activite')) {
                obj['activite'] = ApiClient.convertToType(data['activite'], 'String');
            }
            if (data.hasOwnProperty('date_debut_activite')) {
                obj['date_debut_activite'] = ApiClient.convertToType(data['date_debut_activite'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Greffe de publication.
 * @member {String} rcs
 */
BodaccCreation.prototype['rcs'] = undefined;

/**
 * Nom de l'entreprise concernée par la publication. Correspond à la dénomination en cas de personne morale et à nom + prenom en cas de personne physique.
 * @member {String} nom_entreprise
 */
BodaccCreation.prototype['nom_entreprise'] = undefined;

/**
 * Vrai si l'entreprise concernée par la publication est une personne morale, faux si c'est une personne physique.
 * @member {Boolean} personne_morale
 */
BodaccCreation.prototype['personne_morale'] = undefined;

/**
 * Dénomination de l'entreprise concernée par la publication (uniquement en cas de personne morale).
 * @member {String} denomination
 */
BodaccCreation.prototype['denomination'] = undefined;

/**
 * Nom de la personne physique concernée par la publication (uniquement en cas de personne physique).
 * @member {String} nom
 */
BodaccCreation.prototype['nom'] = undefined;

/**
 * Prénom de la personne physique concernée par la publication (uniquement en cas de personne physique).
 * @member {String} prenom
 */
BodaccCreation.prototype['prenom'] = undefined;

/**
 * Administration (dans le cas d'une personne morale).
 * @member {String} administration
 */
BodaccCreation.prototype['administration'] = undefined;

/**
 * Adresse de l'entreprise concernée par la publication.
 * @member {String} adresse
 */
BodaccCreation.prototype['adresse'] = undefined;

/**
 * Capital de l'entreprise concernée par la publication.
 * @member {Number} capital
 */
BodaccCreation.prototype['capital'] = undefined;

/**
 * Activité de l'entreprise concernée par la publication.
 * @member {String} activite
 */
BodaccCreation.prototype['activite'] = undefined;

/**
 * Date de début d'activité de l'entreprise concernée par la publication, au format AAAA-MM-JJ.
 * @member {String} date_debut_activite
 */
BodaccCreation.prototype['date_debut_activite'] = undefined;


// Implement Bodacc interface:
/**
 * Numéro de parution de la publication.
 * @member {String} numero_parution
 */
Bodacc.prototype['numero_parution'] = undefined;
/**
 * Date de la publication, au format AAAA-MM-JJ.
 * @member {String} date
 */
Bodacc.prototype['date'] = undefined;
/**
 * Numéro d'annonce de la publication.
 * @member {String} numero_annonce
 */
Bodacc.prototype['numero_annonce'] = undefined;
/**
 * Bodacc de la publication (A, B ou C).
 * @member {String} bodacc
 */
Bodacc.prototype['bodacc'] = undefined;
/**
 * Type de la publication parmi la liste suivante : Création, Immatriculation, Modification, Vente, Radiation, Procédure collective, Dépôt des comptes.
 * @member {String} type
 */
Bodacc.prototype['type'] = undefined;
// Implement BodaccCreationAllOf interface:
/**
 * Greffe de publication.
 * @member {String} rcs
 */
BodaccCreationAllOf.prototype['rcs'] = undefined;
/**
 * Nom de l'entreprise concernée par la publication. Correspond à la dénomination en cas de personne morale et à nom + prenom en cas de personne physique.
 * @member {String} nom_entreprise
 */
BodaccCreationAllOf.prototype['nom_entreprise'] = undefined;
/**
 * Vrai si l'entreprise concernée par la publication est une personne morale, faux si c'est une personne physique.
 * @member {Boolean} personne_morale
 */
BodaccCreationAllOf.prototype['personne_morale'] = undefined;
/**
 * Dénomination de l'entreprise concernée par la publication (uniquement en cas de personne morale).
 * @member {String} denomination
 */
BodaccCreationAllOf.prototype['denomination'] = undefined;
/**
 * Nom de la personne physique concernée par la publication (uniquement en cas de personne physique).
 * @member {String} nom
 */
BodaccCreationAllOf.prototype['nom'] = undefined;
/**
 * Prénom de la personne physique concernée par la publication (uniquement en cas de personne physique).
 * @member {String} prenom
 */
BodaccCreationAllOf.prototype['prenom'] = undefined;
/**
 * Administration (dans le cas d'une personne morale).
 * @member {String} administration
 */
BodaccCreationAllOf.prototype['administration'] = undefined;
/**
 * Adresse de l'entreprise concernée par la publication.
 * @member {String} adresse
 */
BodaccCreationAllOf.prototype['adresse'] = undefined;
/**
 * Capital de l'entreprise concernée par la publication.
 * @member {Number} capital
 */
BodaccCreationAllOf.prototype['capital'] = undefined;
/**
 * Activité de l'entreprise concernée par la publication.
 * @member {String} activite
 */
BodaccCreationAllOf.prototype['activite'] = undefined;
/**
 * Date de début d'activité de l'entreprise concernée par la publication, au format AAAA-MM-JJ.
 * @member {String} date_debut_activite
 */
BodaccCreationAllOf.prototype['date_debut_activite'] = undefined;




export default BodaccCreation;

