/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Bodacc from './Bodacc';
import BodaccProcedureCollectiveAllOf from './BodaccProcedureCollectiveAllOf';

/**
 * The BodaccProcedureCollective model module.
 * @module model/BodaccProcedureCollective
 * @version 2.3.0
 */
class BodaccProcedureCollective {
    /**
     * Constructs a new <code>BodaccProcedureCollective</code>.
     * @alias module:model/BodaccProcedureCollective
     * @extends module:model/Bodacc
     * @implements module:model/Bodacc
     * @implements module:model/BodaccProcedureCollectiveAllOf
     */
    constructor() { 
        Bodacc.initialize(this);BodaccProcedureCollectiveAllOf.initialize(this);
        BodaccProcedureCollective.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BodaccProcedureCollective</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BodaccProcedureCollective} obj Optional instance to populate.
     * @return {module:model/BodaccProcedureCollective} The populated <code>BodaccProcedureCollective</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BodaccProcedureCollective();
            Bodacc.constructFromObject(data, obj);
            Bodacc.constructFromObject(data, obj);
            BodaccProcedureCollectiveAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('famille')) {
                obj['famille'] = ApiClient.convertToType(data['famille'], 'String');
            }
            if (data.hasOwnProperty('nature')) {
                obj['nature'] = ApiClient.convertToType(data['nature'], 'String');
            }
            if (data.hasOwnProperty('complement_jugement')) {
                obj['complement_jugement'] = ApiClient.convertToType(data['complement_jugement'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Famille de la procédure collective
 * @member {String} famille
 */
BodaccProcedureCollective.prototype['famille'] = undefined;

/**
 * Nature de la procédure collective
 * @member {String} nature
 */
BodaccProcedureCollective.prototype['nature'] = undefined;

/**
 * Complément sur le jugement de procédure collective
 * @member {String} complement_jugement
 */
BodaccProcedureCollective.prototype['complement_jugement'] = undefined;


// Implement Bodacc interface:
/**
 * Numéro de parution de la publication.
 * @member {String} numero_parution
 */
Bodacc.prototype['numero_parution'] = undefined;
/**
 * Date de la publication, au format AAAA-MM-JJ.
 * @member {String} date
 */
Bodacc.prototype['date'] = undefined;
/**
 * Numéro d'annonce de la publication.
 * @member {String} numero_annonce
 */
Bodacc.prototype['numero_annonce'] = undefined;
/**
 * Bodacc de la publication (A, B ou C).
 * @member {String} bodacc
 */
Bodacc.prototype['bodacc'] = undefined;
/**
 * Type de la publication parmi la liste suivante : Création, Immatriculation, Modification, Vente, Radiation, Procédure collective, Dépôt des comptes.
 * @member {String} type
 */
Bodacc.prototype['type'] = undefined;
// Implement BodaccProcedureCollectiveAllOf interface:
/**
 * Famille de la procédure collective
 * @member {String} famille
 */
BodaccProcedureCollectiveAllOf.prototype['famille'] = undefined;
/**
 * Nature de la procédure collective
 * @member {String} nature
 */
BodaccProcedureCollectiveAllOf.prototype['nature'] = undefined;
/**
 * Complément sur le jugement de procédure collective
 * @member {String} complement_jugement
 */
BodaccProcedureCollectiveAllOf.prototype['complement_jugement'] = undefined;




export default BodaccProcedureCollective;

