/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Document from './Document';
import DocumentComptesAllOf from './DocumentComptesAllOf';

/**
 * The DocumentComptes model module.
 * @module model/DocumentComptes
 * @version 2.3.0
 */
class DocumentComptes {
    /**
     * Constructs a new <code>DocumentComptes</code>.
     * @alias module:model/DocumentComptes
     * @extends module:model/Document
     * @implements module:model/Document
     * @implements module:model/DocumentComptesAllOf
     */
    constructor() { 
        Document.initialize(this);DocumentComptesAllOf.initialize(this);
        DocumentComptes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentComptes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentComptes} obj Optional instance to populate.
     * @return {module:model/DocumentComptes} The populated <code>DocumentComptes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentComptes();
            Document.constructFromObject(data, obj);
            Document.constructFromObject(data, obj);
            DocumentComptesAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('date_cloture')) {
                obj['date_cloture'] = ApiClient.convertToType(data['date_cloture'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * Date de clôture des comptes, au format AAAA-MM-JJ.
 * @member {Date} date_cloture
 */
DocumentComptes.prototype['date_cloture'] = undefined;


// Implement Document interface:
/**
 * Type de document
 * @member {module:model/Document.TypeEnum} type
 */
Document.prototype['type'] = undefined;
/**
 * Date de dépôt du document
 * @member {Date} date_depot
 */
Document.prototype['date_depot'] = undefined;
/**
 * Mentions de la recherche dans le document.
 * @member {Array.<String>} mentions
 */
Document.prototype['mentions'] = undefined;
// Implement DocumentComptesAllOf interface:
/**
 * Date de clôture des comptes, au format AAAA-MM-JJ.
 * @member {Date} date_cloture
 */
DocumentComptesAllOf.prototype['date_cloture'] = undefined;




export default DocumentComptes;

