/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentActeAllOfTitres from './DocumentActeAllOfTitres';

/**
 * The DocumentActeAllOf model module.
 * @module model/DocumentActeAllOf
 * @version 2.3.0
 */
class DocumentActeAllOf {
    /**
     * Constructs a new <code>DocumentActeAllOf</code>.
     * @alias module:model/DocumentActeAllOf
     */
    constructor() { 
        
        DocumentActeAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentActeAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentActeAllOf} obj Optional instance to populate.
     * @return {module:model/DocumentActeAllOf} The populated <code>DocumentActeAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentActeAllOf();

            if (data.hasOwnProperty('titres')) {
                obj['titres'] = ApiClient.convertToType(data['titres'], [DocumentActeAllOfTitres]);
            }
        }
        return obj;
    }


}

/**
 * Titres des actes associés au document
 * @member {Array.<module:model/DocumentActeAllOfTitres>} titres
 */
DocumentActeAllOf.prototype['titres'] = undefined;






export default DocumentActeAllOf;

