/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntrepriseFicheAllOfComptes model module.
 * @module model/EntrepriseFicheAllOfComptes
 * @version 2.3.0
 */
class EntrepriseFicheAllOfComptes {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfComptes</code>.
     * @alias module:model/EntrepriseFicheAllOfComptes
     */
    constructor() { 
        
        EntrepriseFicheAllOfComptes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfComptes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfComptes} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfComptes} The populated <code>EntrepriseFicheAllOfComptes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfComptes();

            if (data.hasOwnProperty('date_depot')) {
                obj['date_depot'] = ApiClient.convertToType(data['date_depot'], 'Date');
            }
            if (data.hasOwnProperty('date_depot_formate')) {
                obj['date_depot_formate'] = ApiClient.convertToType(data['date_depot_formate'], 'String');
            }
            if (data.hasOwnProperty('date_cloture')) {
                obj['date_cloture'] = ApiClient.convertToType(data['date_cloture'], 'Date');
            }
            if (data.hasOwnProperty('annee_cloture')) {
                obj['annee_cloture'] = ApiClient.convertToType(data['annee_cloture'], 'Number');
            }
            if (data.hasOwnProperty('confidentialite')) {
                obj['confidentialite'] = ApiClient.convertToType(data['confidentialite'], 'Boolean');
            }
            if (data.hasOwnProperty('confidentialite_compte_de_resultat')) {
                obj['confidentialite_compte_de_resultat'] = ApiClient.convertToType(data['confidentialite_compte_de_resultat'], 'Boolean');
            }
            if (data.hasOwnProperty('disponible')) {
                obj['disponible'] = ApiClient.convertToType(data['disponible'], 'Boolean');
            }
            if (data.hasOwnProperty('nom_fichier_pdf')) {
                obj['nom_fichier_pdf'] = ApiClient.convertToType(data['nom_fichier_pdf'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('disponible_xlsx')) {
                obj['disponible_xlsx'] = ApiClient.convertToType(data['disponible_xlsx'], 'Boolean');
            }
            if (data.hasOwnProperty('nom_fichier_xlsx')) {
                obj['nom_fichier_xlsx'] = ApiClient.convertToType(data['nom_fichier_xlsx'], 'String');
            }
            if (data.hasOwnProperty('token_xlsx')) {
                obj['token_xlsx'] = ApiClient.convertToType(data['token_xlsx'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Date de dépôt des comptes.
 * @member {Date} date_depot
 */
EntrepriseFicheAllOfComptes.prototype['date_depot'] = undefined;

/**
 * Date de dépôt formatée des comptes.
 * @member {String} date_depot_formate
 */
EntrepriseFicheAllOfComptes.prototype['date_depot_formate'] = undefined;

/**
 * Date de clôture des comptes, au format AAAA-MM-JJ.
 * @member {Date} date_cloture
 */
EntrepriseFicheAllOfComptes.prototype['date_cloture'] = undefined;

/**
 * Année de clôture des comptes.
 * @member {Number} annee_cloture
 */
EntrepriseFicheAllOfComptes.prototype['annee_cloture'] = undefined;

/**
 * Confidentialité totale des comptes.
 * @member {Boolean} confidentialite
 */
EntrepriseFicheAllOfComptes.prototype['confidentialite'] = undefined;

/**
 * Confidentialité partielle des comptes (seul le compte de résultat est confidentiel, le reste des comptes sont disponibles).
 * @member {Boolean} confidentialite_compte_de_resultat
 */
EntrepriseFicheAllOfComptes.prototype['confidentialite_compte_de_resultat'] = undefined;

/**
 * Disponibilité des comptes au format PDF.
 * @member {Boolean} disponible
 */
EntrepriseFicheAllOfComptes.prototype['disponible'] = undefined;

/**
 * Nom du fichier PDF des comptes.
 * @member {String} nom_fichier_pdf
 */
EntrepriseFicheAllOfComptes.prototype['nom_fichier_pdf'] = undefined;

/**
 * Token des comptes.
 * @member {String} token
 */
EntrepriseFicheAllOfComptes.prototype['token'] = undefined;

/**
 * Disponibilité des comptes au format XLSX.
 * @member {Boolean} disponible_xlsx
 */
EntrepriseFicheAllOfComptes.prototype['disponible_xlsx'] = undefined;

/**
 * Nom du fichier XLSX des comptes.
 * @member {String} nom_fichier_xlsx
 */
EntrepriseFicheAllOfComptes.prototype['nom_fichier_xlsx'] = undefined;

/**
 * Token des comptes XLSX.
 * @member {String} token_xlsx
 */
EntrepriseFicheAllOfComptes.prototype['token_xlsx'] = undefined;






export default EntrepriseFicheAllOfComptes;

