/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntrepriseFicheAllOfDetailsSocieteDeGestion model module.
 * @module model/EntrepriseFicheAllOfDetailsSocieteDeGestion
 * @version 2.3.0
 */
class EntrepriseFicheAllOfDetailsSocieteDeGestion {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfDetailsSocieteDeGestion</code>.
     * Détails sur la société de gestion, le cas échéant.
     * @alias module:model/EntrepriseFicheAllOfDetailsSocieteDeGestion
     */
    constructor() { 
        
        EntrepriseFicheAllOfDetailsSocieteDeGestion.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfDetailsSocieteDeGestion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfDetailsSocieteDeGestion} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfDetailsSocieteDeGestion} The populated <code>EntrepriseFicheAllOfDetailsSocieteDeGestion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfDetailsSocieteDeGestion();

            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('siren')) {
                obj['siren'] = ApiClient.convertToType(data['siren'], 'String');
            }
            if (data.hasOwnProperty('greffe')) {
                obj['greffe'] = ApiClient.convertToType(data['greffe'], 'String');
            }
            if (data.hasOwnProperty('adresse')) {
                obj['adresse'] = ApiClient.convertToType(data['adresse'], 'String');
            }
            if (data.hasOwnProperty('code_postal')) {
                obj['code_postal'] = ApiClient.convertToType(data['code_postal'], 'String');
            }
            if (data.hasOwnProperty('ville')) {
                obj['ville'] = ApiClient.convertToType(data['ville'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Nom de la société de gestion.
 * @member {String} nom
 */
EntrepriseFicheAllOfDetailsSocieteDeGestion.prototype['nom'] = undefined;

/**
 * SIREN de la société de gestion.
 * @member {String} siren
 */
EntrepriseFicheAllOfDetailsSocieteDeGestion.prototype['siren'] = undefined;

/**
 * Greffe de la société de gestion.
 * @member {String} greffe
 */
EntrepriseFicheAllOfDetailsSocieteDeGestion.prototype['greffe'] = undefined;

/**
 * Adresse de la société de gestion.
 * @member {String} adresse
 */
EntrepriseFicheAllOfDetailsSocieteDeGestion.prototype['adresse'] = undefined;

/**
 * Code postal de la société de gestion.
 * @member {String} code_postal
 */
EntrepriseFicheAllOfDetailsSocieteDeGestion.prototype['code_postal'] = undefined;

/**
 * Ville de la société de gestion.
 * @member {String} ville
 */
EntrepriseFicheAllOfDetailsSocieteDeGestion.prototype['ville'] = undefined;






export default EntrepriseFicheAllOfDetailsSocieteDeGestion;

