/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Bodacc from './Bodacc';

/**
 * The EntrepriseFicheAllOfProceduresCollectives model module.
 * @module model/EntrepriseFicheAllOfProceduresCollectives
 * @version 2.3.0
 */
class EntrepriseFicheAllOfProceduresCollectives {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfProceduresCollectives</code>.
     * @alias module:model/EntrepriseFicheAllOfProceduresCollectives
     */
    constructor() { 
        
        EntrepriseFicheAllOfProceduresCollectives.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfProceduresCollectives</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfProceduresCollectives} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfProceduresCollectives} The populated <code>EntrepriseFicheAllOfProceduresCollectives</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfProceduresCollectives();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('date_debut')) {
                obj['date_debut'] = ApiClient.convertToType(data['date_debut'], 'String');
            }
            if (data.hasOwnProperty('date_fin')) {
                obj['date_fin'] = ApiClient.convertToType(data['date_fin'], 'String');
            }
            if (data.hasOwnProperty('publications_bodacc')) {
                obj['publications_bodacc'] = ApiClient.convertToType(data['publications_bodacc'], [Bodacc]);
            }
        }
        return obj;
    }


}

/**
 * Type de la procédure collective.
 * @member {module:model/EntrepriseFicheAllOfProceduresCollectives.TypeEnum} type
 */
EntrepriseFicheAllOfProceduresCollectives.prototype['type'] = undefined;

/**
 * Date de début de la procédure collective, au format AAAA-MM-JJ.
 * @member {String} date_debut
 */
EntrepriseFicheAllOfProceduresCollectives.prototype['date_debut'] = undefined;

/**
 * Date de fin de la procédure collective, au format AAAA-MM-JJ.
 * @member {String} date_fin
 */
EntrepriseFicheAllOfProceduresCollectives.prototype['date_fin'] = undefined;

/**
 * Liste des publications relatives à la procédure collective.
 * @member {Array.<module:model/Bodacc>} publications_bodacc
 */
EntrepriseFicheAllOfProceduresCollectives.prototype['publications_bodacc'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
EntrepriseFicheAllOfProceduresCollectives['TypeEnum'] = {

    /**
     * value: "Redressement judiciaire"
     * @const
     */
    "Redressement judiciaire": "Redressement judiciaire",

    /**
     * value: "Liquidation judiciaire ou Procédure de sauvegarde"
     * @const
     */
    "Liquidation judiciaire ou Procédure de sauvegarde": "Liquidation judiciaire ou Procédure de sauvegarde"
};



export default EntrepriseFicheAllOfProceduresCollectives;

