/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes from './EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes';
import EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes from './EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes';

/**
 * The EntrepriseFicheAllOfDetailsPartsVocationTitulaire model module.
 * @module model/EntrepriseFicheAllOfDetailsPartsVocationTitulaire
 * @version 2.3.0
 */
class EntrepriseFicheAllOfDetailsPartsVocationTitulaire {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfDetailsPartsVocationTitulaire</code>.
     * Détails des parts dont le bénéficiaire effectif a vocation à devenir titulaire.
     * @alias module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaire
     */
    constructor() { 
        
        EntrepriseFicheAllOfDetailsPartsVocationTitulaire.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfDetailsPartsVocationTitulaire</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaire} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaire} The populated <code>EntrepriseFicheAllOfDetailsPartsVocationTitulaire</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfDetailsPartsVocationTitulaire();

            if (data.hasOwnProperty('pourcentage_directes')) {
                obj['pourcentage_directes'] = ApiClient.convertToType(data['pourcentage_directes'], 'Number');
            }
            if (data.hasOwnProperty('pourcentage_indirectes')) {
                obj['pourcentage_indirectes'] = ApiClient.convertToType(data['pourcentage_indirectes'], 'Number');
            }
            if (data.hasOwnProperty('details_directes')) {
                obj['details_directes'] = EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes.constructFromObject(data['details_directes']);
            }
            if (data.hasOwnProperty('details_indirectes')) {
                obj['details_indirectes'] = EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes.constructFromObject(data['details_indirectes']);
            }
        }
        return obj;
    }


}

/**
 * Parts dont le bénéficiaire effectif a vocation à devenir titulaire de façon directe, en pourcentage des parts totales.
 * @member {Number} pourcentage_directes
 */
EntrepriseFicheAllOfDetailsPartsVocationTitulaire.prototype['pourcentage_directes'] = undefined;

/**
 * Parts dont le bénéficiaire effectif a vocation à devenir titulaire de façon indirecte, en pourcentage des parts totales.
 * @member {Number} pourcentage_indirectes
 */
EntrepriseFicheAllOfDetailsPartsVocationTitulaire.prototype['pourcentage_indirectes'] = undefined;

/**
 * @member {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes} details_directes
 */
EntrepriseFicheAllOfDetailsPartsVocationTitulaire.prototype['details_directes'] = undefined;

/**
 * @member {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes} details_indirectes
 */
EntrepriseFicheAllOfDetailsPartsVocationTitulaire.prototype['details_indirectes'] = undefined;






export default EntrepriseFicheAllOfDetailsPartsVocationTitulaire;

