/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntrepriseFicheAllOfDerniersStatuts model module.
 * @module model/EntrepriseFicheAllOfDerniersStatuts
 * @version 2.3.0
 */
class EntrepriseFicheAllOfDerniersStatuts {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfDerniersStatuts</code>.
     * Liste des statuts de l&#39;entreprise.
     * @alias module:model/EntrepriseFicheAllOfDerniersStatuts
     */
    constructor() { 
        
        EntrepriseFicheAllOfDerniersStatuts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfDerniersStatuts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfDerniersStatuts} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfDerniersStatuts} The populated <code>EntrepriseFicheAllOfDerniersStatuts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfDerniersStatuts();

            if (data.hasOwnProperty('date_depot')) {
                obj['date_depot'] = ApiClient.convertToType(data['date_depot'], 'Date');
            }
            if (data.hasOwnProperty('date_depot_formate')) {
                obj['date_depot_formate'] = ApiClient.convertToType(data['date_depot_formate'], 'String');
            }
            if (data.hasOwnProperty('disponible')) {
                obj['disponible'] = ApiClient.convertToType(data['disponible'], 'Boolean');
            }
            if (data.hasOwnProperty('nom_fichier_pdf')) {
                obj['nom_fichier_pdf'] = ApiClient.convertToType(data['nom_fichier_pdf'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('decision')) {
                obj['decision'] = ApiClient.convertToType(data['decision'], 'String');
            }
            if (data.hasOwnProperty('date_acte')) {
                obj['date_acte'] = ApiClient.convertToType(data['date_acte'], 'Date');
            }
            if (data.hasOwnProperty('date_acte_formate')) {
                obj['date_acte_formate'] = ApiClient.convertToType(data['date_acte_formate'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Date de dépôt des statuts, au format AAAA-MM-JJ.
 * @member {Date} date_depot
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['date_depot'] = undefined;

/**
 * Date de dépôt formaté des statuts, au format JJ/MM/AAAA.
 * @member {String} date_depot_formate
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['date_depot_formate'] = undefined;

/**
 * Disponibilité des statuts.
 * @member {Boolean} disponible
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['disponible'] = undefined;

/**
 * Nom du fichier pdf des statuts.
 * @member {String} nom_fichier_pdf
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['nom_fichier_pdf'] = undefined;

/**
 * Token des statuts.
 * @member {String} token
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['token'] = undefined;

/**
 * Champ \"type\" du document contenant les statuts.
 * @member {String} type
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['type'] = undefined;

/**
 * Champ \"decision\" du document contenant les statuts.
 * @member {String} decision
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['decision'] = undefined;

/**
 * Date de publication des statuts, au format AAAA-MM-JJ.
 * @member {Date} date_acte
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['date_acte'] = undefined;

/**
 * Date de publication des statuts, au format JJ/MM/AAAA.
 * @member {String} date_acte_formate
 */
EntrepriseFicheAllOfDerniersStatuts.prototype['date_acte_formate'] = undefined;






export default EntrepriseFicheAllOfDerniersStatuts;

