/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntrepriseFicheAllOfExtraitImmatriculation model module.
 * @module model/EntrepriseFicheAllOfExtraitImmatriculation
 * @version 2.3.0
 */
class EntrepriseFicheAllOfExtraitImmatriculation {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfExtraitImmatriculation</code>.
     * Extrait d&#39;immatriculation de l&#39;entreprise.
     * @alias module:model/EntrepriseFicheAllOfExtraitImmatriculation
     */
    constructor() { 
        
        EntrepriseFicheAllOfExtraitImmatriculation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfExtraitImmatriculation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfExtraitImmatriculation} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfExtraitImmatriculation} The populated <code>EntrepriseFicheAllOfExtraitImmatriculation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfExtraitImmatriculation();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Token
 * @member {String} token
 */
EntrepriseFicheAllOfExtraitImmatriculation.prototype['token'] = undefined;






export default EntrepriseFicheAllOfExtraitImmatriculation;

