/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntrepriseFicheAllOfRnm model module.
 * @module model/EntrepriseFicheAllOfRnm
 * @version 2.3.0
 */
class EntrepriseFicheAllOfRnm {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfRnm</code>.
     * Informations sur l&#39;immatriculation de l&#39;entreprise au Répertoire des Métiers.
     * @alias module:model/EntrepriseFicheAllOfRnm
     */
    constructor() { 
        
        EntrepriseFicheAllOfRnm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfRnm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfRnm} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfRnm} The populated <code>EntrepriseFicheAllOfRnm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfRnm();

            if (data.hasOwnProperty('date_immatriculation')) {
                obj['date_immatriculation'] = ApiClient.convertToType(data['date_immatriculation'], 'String');
            }
            if (data.hasOwnProperty('date_radiation')) {
                obj['date_radiation'] = ApiClient.convertToType(data['date_radiation'], 'String');
            }
            if (data.hasOwnProperty('date_debut_activite')) {
                obj['date_debut_activite'] = ApiClient.convertToType(data['date_debut_activite'], 'String');
            }
            if (data.hasOwnProperty('date_cessation_activite')) {
                obj['date_cessation_activite'] = ApiClient.convertToType(data['date_cessation_activite'], 'String');
            }
            if (data.hasOwnProperty('chambre_des_metiers')) {
                obj['chambre_des_metiers'] = ApiClient.convertToType(data['chambre_des_metiers'], 'String');
            }
            if (data.hasOwnProperty('qualification')) {
                obj['qualification'] = ApiClient.convertToType(data['qualification'], 'String');
            }
            if (data.hasOwnProperty('derniere_mise_a_jour')) {
                obj['derniere_mise_a_jour'] = ApiClient.convertToType(data['derniere_mise_a_jour'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Date d'immatriculation au Répertoire des Métiers, au format AAAA-MM-JJ.
 * @member {String} date_immatriculation
 */
EntrepriseFicheAllOfRnm.prototype['date_immatriculation'] = undefined;

/**
 * Date de radiation du Répertoire des Métiers, le cas échéant, au format AAAA-MM-JJ.
 * @member {String} date_radiation
 */
EntrepriseFicheAllOfRnm.prototype['date_radiation'] = undefined;

/**
 * Date de début d'activé déclarée au Répertoire des Métiers, au format AAAA-MM-JJ.
 * @member {String} date_debut_activite
 */
EntrepriseFicheAllOfRnm.prototype['date_debut_activite'] = undefined;

/**
 * Date de cessation d'activité déclarée au Répertoire des Métiers, le cas échéant, au format AAAA-MM-JJ.
 * @member {String} date_cessation_activite
 */
EntrepriseFicheAllOfRnm.prototype['date_cessation_activite'] = undefined;

/**
 * Chambre des métiers où l'entreprise est immatriculée.
 * @member {String} chambre_des_metiers
 */
EntrepriseFicheAllOfRnm.prototype['chambre_des_metiers'] = undefined;

/**
 * Qualification retenue par le Répertoire des Métiers.
 * @member {String} qualification
 */
EntrepriseFicheAllOfRnm.prototype['qualification'] = undefined;

/**
 * Date de dernière mise à jour de l'entreprise au Répertoire des Métiers, au format AAAA-MM-JJ.
 * @member {String} derniere_mise_a_jour
 */
EntrepriseFicheAllOfRnm.prototype['derniere_mise_a_jour'] = undefined;






export default EntrepriseFicheAllOfRnm;

