/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EntrepriseFicheAllOfEvenements model module.
 * @module model/EntrepriseFicheAllOfEvenements
 * @version 2.3.0
 */
class EntrepriseFicheAllOfEvenements {
    /**
     * Constructs a new <code>EntrepriseFicheAllOfEvenements</code>.
     * @alias module:model/EntrepriseFicheAllOfEvenements
     */
    constructor() { 
        
        EntrepriseFicheAllOfEvenements.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EntrepriseFicheAllOfEvenements</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntrepriseFicheAllOfEvenements} obj Optional instance to populate.
     * @return {module:model/EntrepriseFicheAllOfEvenements} The populated <code>EntrepriseFicheAllOfEvenements</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntrepriseFicheAllOfEvenements();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('identifiant_evenement')) {
                obj['identifiant_evenement'] = ApiClient.convertToType(data['identifiant_evenement'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('numero_bopi')) {
                obj['numero_bopi'] = ApiClient.convertToType(data['numero_bopi'], 'String');
            }
            if (data.hasOwnProperty('date_bopi')) {
                obj['date_bopi'] = ApiClient.convertToType(data['date_bopi'], 'String');
            }
            if (data.hasOwnProperty('beneficiaire')) {
                obj['beneficiaire'] = ApiClient.convertToType(data['beneficiaire'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Type d'événement.
 * @member {String} type
 */
EntrepriseFicheAllOfEvenements.prototype['type'] = undefined;

/**
 * Identifiant de l'événement.
 * @member {String} identifiant_evenement
 */
EntrepriseFicheAllOfEvenements.prototype['identifiant_evenement'] = undefined;

/**
 * Référence de l'événement.
 * @member {String} reference
 */
EntrepriseFicheAllOfEvenements.prototype['reference'] = undefined;

/**
 * Date de l'événement, au format AAAA-MM-JJ.
 * @member {String} date
 */
EntrepriseFicheAllOfEvenements.prototype['date'] = undefined;

/**
 * Numéro du BOPI dans lequel l'événement a été publié.
 * @member {String} numero_bopi
 */
EntrepriseFicheAllOfEvenements.prototype['numero_bopi'] = undefined;

/**
 * Date de publication du BOPI au format AAAA-MM-JJ.
 * @member {String} date_bopi
 */
EntrepriseFicheAllOfEvenements.prototype['date_bopi'] = undefined;

/**
 * Bénéficiaire associé à l'événement.
 * @member {String} beneficiaire
 */
EntrepriseFicheAllOfEvenements.prototype['beneficiaire'] = undefined;






export default EntrepriseFicheAllOfEvenements;

