/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EtablissementRecherche model module.
 * @module model/EtablissementRecherche
 * @version 2.3.0
 */
class EtablissementRecherche {
    /**
     * Constructs a new <code>EtablissementRecherche</code>.
     * @alias module:model/EtablissementRecherche
     */
    constructor() { 
        
        EtablissementRecherche.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EtablissementRecherche</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EtablissementRecherche} obj Optional instance to populate.
     * @return {module:model/EtablissementRecherche} The populated <code>EtablissementRecherche</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EtablissementRecherche();

            if (data.hasOwnProperty('siret')) {
                obj['siret'] = ApiClient.convertToType(data['siret'], 'String');
            }
            if (data.hasOwnProperty('siret_formate')) {
                obj['siret_formate'] = ApiClient.convertToType(data['siret_formate'], 'String');
            }
            if (data.hasOwnProperty('nic')) {
                obj['nic'] = ApiClient.convertToType(data['nic'], 'String');
            }
            if (data.hasOwnProperty('numero_voie')) {
                obj['numero_voie'] = ApiClient.convertToType(data['numero_voie'], 'Number');
            }
            if (data.hasOwnProperty('indice_repetition')) {
                obj['indice_repetition'] = ApiClient.convertToType(data['indice_repetition'], 'String');
            }
            if (data.hasOwnProperty('type_voie')) {
                obj['type_voie'] = ApiClient.convertToType(data['type_voie'], 'String');
            }
            if (data.hasOwnProperty('libelle_voie')) {
                obj['libelle_voie'] = ApiClient.convertToType(data['libelle_voie'], 'String');
            }
            if (data.hasOwnProperty('complement_adresse')) {
                obj['complement_adresse'] = ApiClient.convertToType(data['complement_adresse'], 'String');
            }
            if (data.hasOwnProperty('adresse_ligne_1')) {
                obj['adresse_ligne_1'] = ApiClient.convertToType(data['adresse_ligne_1'], 'String');
            }
            if (data.hasOwnProperty('adresse_ligne_2')) {
                obj['adresse_ligne_2'] = ApiClient.convertToType(data['adresse_ligne_2'], 'String');
            }
            if (data.hasOwnProperty('code_postal')) {
                obj['code_postal'] = ApiClient.convertToType(data['code_postal'], 'String');
            }
            if (data.hasOwnProperty('ville')) {
                obj['ville'] = ApiClient.convertToType(data['ville'], 'String');
            }
            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Numéro siret de l'établissement au format xxxxxxxxxxxxxx.
 * @member {String} siret
 */
EtablissementRecherche.prototype['siret'] = undefined;

/**
 * Numéro siret de l'établissement au format xxx xxx xxx xxxxx.
 * @member {String} siret_formate
 */
EtablissementRecherche.prototype['siret_formate'] = undefined;

/**
 * Numéro NIC de l'établissement.
 * @member {String} nic
 */
EtablissementRecherche.prototype['nic'] = undefined;

/**
 * Numéro de voie de l'établissement.
 * @member {Number} numero_voie
 */
EtablissementRecherche.prototype['numero_voie'] = undefined;

/**
 * Indice de répétition de l'établissement.
 * @member {String} indice_repetition
 */
EtablissementRecherche.prototype['indice_repetition'] = undefined;

/**
 * Type de voie de l'établissement.
 * @member {String} type_voie
 */
EtablissementRecherche.prototype['type_voie'] = undefined;

/**
 * Libellé de la voie de l'établissement.
 * @member {String} libelle_voie
 */
EtablissementRecherche.prototype['libelle_voie'] = undefined;

/**
 * Complément d'adresse de l'établissement.
 * @member {String} complement_adresse
 */
EtablissementRecherche.prototype['complement_adresse'] = undefined;

/**
 * Première ligne de l'adresse de l'établissement. Correspond à l'ensemble des données numero_voie, indice_repetition, type_voie et libelle_voie.
 * @member {String} adresse_ligne_1
 */
EtablissementRecherche.prototype['adresse_ligne_1'] = undefined;

/**
 * Seconde ligne de l'adresse de l'établissement. Est égal à complement_adresse
 * @member {String} adresse_ligne_2
 */
EtablissementRecherche.prototype['adresse_ligne_2'] = undefined;

/**
 * Code postal de l'établissement.
 * @member {String} code_postal
 */
EtablissementRecherche.prototype['code_postal'] = undefined;

/**
 * Ville de l'établissement.
 * @member {String} ville
 */
EtablissementRecherche.prototype['ville'] = undefined;

/**
 * Latitude de l'établissement.
 * @member {Number} latitude
 */
EtablissementRecherche.prototype['latitude'] = undefined;

/**
 * Longitude de l'établissement.
 * @member {Number} longitude
 */
EtablissementRecherche.prototype['longitude'] = undefined;






export default EtablissementRecherche;

