/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EtablissementFicheDomiciliation model module.
 * @module model/EtablissementFicheDomiciliation
 * @version 2.3.0
 */
class EtablissementFicheDomiciliation {
    /**
     * Constructs a new <code>EtablissementFicheDomiciliation</code>.
     * @alias module:model/EtablissementFicheDomiciliation
     */
    constructor() { 
        
        EtablissementFicheDomiciliation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EtablissementFicheDomiciliation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EtablissementFicheDomiciliation} obj Optional instance to populate.
     * @return {module:model/EtablissementFicheDomiciliation} The populated <code>EtablissementFicheDomiciliation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EtablissementFicheDomiciliation();

            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('siren')) {
                obj['siren'] = ApiClient.convertToType(data['siren'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Nom de l'entreprise de domiciliation
 * @member {String} nom
 */
EtablissementFicheDomiciliation.prototype['nom'] = undefined;

/**
 * Siren de l'entreprise de domiciliation
 * @member {String} siren
 */
EtablissementFicheDomiciliation.prototype['siren'] = undefined;






export default EtablissementFicheDomiciliation;

