/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonneMarque model module.
 * @module model/PersonneMarque
 * @version 2.3.0
 */
class PersonneMarque {
    /**
     * Constructs a new <code>PersonneMarque</code>.
     * @alias module:model/PersonneMarque
     */
    constructor() { 
        
        PersonneMarque.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonneMarque</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonneMarque} obj Optional instance to populate.
     * @return {module:model/PersonneMarque} The populated <code>PersonneMarque</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonneMarque();

            if (data.hasOwnProperty('siren')) {
                obj['siren'] = ApiClient.convertToType(data['siren'], 'String');
            }
            if (data.hasOwnProperty('entite_legale')) {
                obj['entite_legale'] = ApiClient.convertToType(data['entite_legale'], 'String');
            }
            if (data.hasOwnProperty('nom')) {
                obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
            }
            if (data.hasOwnProperty('batiment')) {
                obj['batiment'] = ApiClient.convertToType(data['batiment'], 'String');
            }
            if (data.hasOwnProperty('rue')) {
                obj['rue'] = ApiClient.convertToType(data['rue'], 'String');
            }
            if (data.hasOwnProperty('ville')) {
                obj['ville'] = ApiClient.convertToType(data['ville'], 'String');
            }
            if (data.hasOwnProperty('boite_postale')) {
                obj['boite_postale'] = ApiClient.convertToType(data['boite_postale'], 'String');
            }
            if (data.hasOwnProperty('code_postal')) {
                obj['code_postal'] = ApiClient.convertToType(data['code_postal'], 'String');
            }
            if (data.hasOwnProperty('code_pays')) {
                obj['code_pays'] = ApiClient.convertToType(data['code_pays'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Siren de l'entité, dans le cas d'une personne morale.
 * @member {String} siren
 */
PersonneMarque.prototype['siren'] = undefined;

/**
 * Entité légale.
 * @member {String} entite_legale
 */
PersonneMarque.prototype['entite_legale'] = undefined;

/**
 * Nom de l'entité.
 * @member {String} nom
 */
PersonneMarque.prototype['nom'] = undefined;

/**
 * Bâtiment de l'entité.
 * @member {String} batiment
 */
PersonneMarque.prototype['batiment'] = undefined;

/**
 * Rue de l'entité.
 * @member {String} rue
 */
PersonneMarque.prototype['rue'] = undefined;

/**
 * Ville de l'entité.
 * @member {String} ville
 */
PersonneMarque.prototype['ville'] = undefined;

/**
 * Boîte postale de l'entité.
 * @member {String} boite_postale
 */
PersonneMarque.prototype['boite_postale'] = undefined;

/**
 * Code postal de l'entité.
 * @member {String} code_postal
 */
PersonneMarque.prototype['code_postal'] = undefined;

/**
 * Code pays de l'entité.
 * @member {String} code_pays
 */
PersonneMarque.prototype['code_pays'] = undefined;






export default PersonneMarque;

