/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Ratios model module.
 * @module model/Ratios
 * @version 2.3.0
 */
class Ratios {
    /**
     * Constructs a new <code>Ratios</code>.
     * @alias module:model/Ratios
     */
    constructor() { 
        
        Ratios.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Ratios</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Ratios} obj Optional instance to populate.
     * @return {module:model/Ratios} The populated <code>Ratios</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Ratios();

            if (data.hasOwnProperty('chiffre_affaires')) {
                obj['chiffre_affaires'] = ApiClient.convertToType(data['chiffre_affaires'], 'Number');
            }
            if (data.hasOwnProperty('resultat')) {
                obj['resultat'] = ApiClient.convertToType(data['resultat'], 'Number');
            }
            if (data.hasOwnProperty('effectif')) {
                obj['effectif'] = ApiClient.convertToType(data['effectif'], 'Number');
            }
            if (data.hasOwnProperty('marge_brute')) {
                obj['marge_brute'] = ApiClient.convertToType(data['marge_brute'], 'Number');
            }
            if (data.hasOwnProperty('excedent_brut_exploitation')) {
                obj['excedent_brut_exploitation'] = ApiClient.convertToType(data['excedent_brut_exploitation'], 'Number');
            }
            if (data.hasOwnProperty('resultat_exploitation')) {
                obj['resultat_exploitation'] = ApiClient.convertToType(data['resultat_exploitation'], 'Number');
            }
            if (data.hasOwnProperty('taux_croissance_chiffre_affaires')) {
                obj['taux_croissance_chiffre_affaires'] = ApiClient.convertToType(data['taux_croissance_chiffre_affaires'], 'Number');
            }
            if (data.hasOwnProperty('taux_marge_brute')) {
                obj['taux_marge_brute'] = ApiClient.convertToType(data['taux_marge_brute'], 'Number');
            }
            if (data.hasOwnProperty('taux_marge_EBITDA')) {
                obj['taux_marge_EBITDA'] = ApiClient.convertToType(data['taux_marge_EBITDA'], 'Number');
            }
            if (data.hasOwnProperty('taux_marge_operationnelle')) {
                obj['taux_marge_operationnelle'] = ApiClient.convertToType(data['taux_marge_operationnelle'], 'Number');
            }
            if (data.hasOwnProperty('BFR')) {
                obj['BFR'] = ApiClient.convertToType(data['BFR'], 'Number');
            }
            if (data.hasOwnProperty('BFR_exploitation')) {
                obj['BFR_exploitation'] = ApiClient.convertToType(data['BFR_exploitation'], 'Number');
            }
            if (data.hasOwnProperty('BFR_hors_exploitation')) {
                obj['BFR_hors_exploitation'] = ApiClient.convertToType(data['BFR_hors_exploitation'], 'Number');
            }
            if (data.hasOwnProperty('BFR_jours_CA')) {
                obj['BFR_jours_CA'] = ApiClient.convertToType(data['BFR_jours_CA'], 'Number');
            }
            if (data.hasOwnProperty('BFR_exploitation_jours_CA')) {
                obj['BFR_exploitation_jours_CA'] = ApiClient.convertToType(data['BFR_exploitation_jours_CA'], 'Number');
            }
            if (data.hasOwnProperty('BFR_hors_exploitation_jours_CA')) {
                obj['BFR_hors_exploitation_jours_CA'] = ApiClient.convertToType(data['BFR_hors_exploitation_jours_CA'], 'Number');
            }
            if (data.hasOwnProperty('delai_paiement_clients_jours')) {
                obj['delai_paiement_clients_jours'] = ApiClient.convertToType(data['delai_paiement_clients_jours'], 'Number');
            }
            if (data.hasOwnProperty('delai_paiement_fournisseurs_jours')) {
                obj['delai_paiement_fournisseurs_jours'] = ApiClient.convertToType(data['delai_paiement_fournisseurs_jours'], 'Number');
            }
            if (data.hasOwnProperty('ratio_stock_CA_jours')) {
                obj['ratio_stock_CA_jours'] = ApiClient.convertToType(data['ratio_stock_CA_jours'], 'Number');
            }
            if (data.hasOwnProperty('capacite_autofinancement')) {
                obj['capacite_autofinancement'] = ApiClient.convertToType(data['capacite_autofinancement'], 'Number');
            }
            if (data.hasOwnProperty('capacite_autofinancement_CA')) {
                obj['capacite_autofinancement_CA'] = ApiClient.convertToType(data['capacite_autofinancement_CA'], 'Number');
            }
            if (data.hasOwnProperty('fonds_roulement_net_global')) {
                obj['fonds_roulement_net_global'] = ApiClient.convertToType(data['fonds_roulement_net_global'], 'Number');
            }
            if (data.hasOwnProperty('couverture_BFR')) {
                obj['couverture_BFR'] = ApiClient.convertToType(data['couverture_BFR'], 'Number');
            }
            if (data.hasOwnProperty('tresorerie')) {
                obj['tresorerie'] = ApiClient.convertToType(data['tresorerie'], 'Number');
            }
            if (data.hasOwnProperty('dettes_financieres')) {
                obj['dettes_financieres'] = ApiClient.convertToType(data['dettes_financieres'], 'Number');
            }
            if (data.hasOwnProperty('capacite_remboursement')) {
                obj['capacite_remboursement'] = ApiClient.convertToType(data['capacite_remboursement'], 'Number');
            }
            if (data.hasOwnProperty('ratio_endettement')) {
                obj['ratio_endettement'] = ApiClient.convertToType(data['ratio_endettement'], 'Number');
            }
            if (data.hasOwnProperty('autonomie_financiere')) {
                obj['autonomie_financiere'] = ApiClient.convertToType(data['autonomie_financiere'], 'Number');
            }
            if (data.hasOwnProperty('taux_levier')) {
                obj['taux_levier'] = ApiClient.convertToType(data['taux_levier'], 'Number');
            }
            if (data.hasOwnProperty('etat_dettes_1_an_au_plus')) {
                obj['etat_dettes_1_an_au_plus'] = ApiClient.convertToType(data['etat_dettes_1_an_au_plus'], 'Number');
            }
            if (data.hasOwnProperty('liquidite_generale')) {
                obj['liquidite_generale'] = ApiClient.convertToType(data['liquidite_generale'], 'Number');
            }
            if (data.hasOwnProperty('couverture_dettes')) {
                obj['couverture_dettes'] = ApiClient.convertToType(data['couverture_dettes'], 'Number');
            }
            if (data.hasOwnProperty('marge_nette')) {
                obj['marge_nette'] = ApiClient.convertToType(data['marge_nette'], 'Number');
            }
            if (data.hasOwnProperty('rentabilite_fonds_propres')) {
                obj['rentabilite_fonds_propres'] = ApiClient.convertToType(data['rentabilite_fonds_propres'], 'Number');
            }
            if (data.hasOwnProperty('rentabilite_economique')) {
                obj['rentabilite_economique'] = ApiClient.convertToType(data['rentabilite_economique'], 'Number');
            }
            if (data.hasOwnProperty('valeur_ajoutee')) {
                obj['valeur_ajoutee'] = ApiClient.convertToType(data['valeur_ajoutee'], 'Number');
            }
            if (data.hasOwnProperty('valeur_ajoutee_CA')) {
                obj['valeur_ajoutee_CA'] = ApiClient.convertToType(data['valeur_ajoutee_CA'], 'Number');
            }
            if (data.hasOwnProperty('salaires_charges_sociales')) {
                obj['salaires_charges_sociales'] = ApiClient.convertToType(data['salaires_charges_sociales'], 'Number');
            }
            if (data.hasOwnProperty('salaires_CA')) {
                obj['salaires_CA'] = ApiClient.convertToType(data['salaires_CA'], 'Number');
            }
            if (data.hasOwnProperty('impots_taxes')) {
                obj['impots_taxes'] = ApiClient.convertToType(data['impots_taxes'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Chiffre d'affaires de l'entreprise.
 * @member {Number} chiffre_affaires
 */
Ratios.prototype['chiffre_affaires'] = undefined;

/**
 * Résultat de l'entreprise.
 * @member {Number} resultat
 */
Ratios.prototype['resultat'] = undefined;

/**
 * Effectif de l'entreprise.
 * @member {Number} effectif
 */
Ratios.prototype['effectif'] = undefined;

/**
 * Marge brute de l'entreprise.
 * @member {Number} marge_brute
 */
Ratios.prototype['marge_brute'] = undefined;

/**
 * Excédent brut d'exploitation (EBITDA) de l'entreprise.
 * @member {Number} excedent_brut_exploitation
 */
Ratios.prototype['excedent_brut_exploitation'] = undefined;

/**
 * Résultat d'exploitation (EBIT) de l'entreprise.
 * @member {Number} resultat_exploitation
 */
Ratios.prototype['resultat_exploitation'] = undefined;

/**
 * Taux de croissance du chiffre d'affaires (en %) de l'entreprise.
 * @member {Number} taux_croissance_chiffre_affaires
 */
Ratios.prototype['taux_croissance_chiffre_affaires'] = undefined;

/**
 * Taux de marge brute (en %) de l'entreprise.
 * @member {Number} taux_marge_brute
 */
Ratios.prototype['taux_marge_brute'] = undefined;

/**
 * Taux de marge d'EBITDA (en %) de l'entreprise.
 * @member {Number} taux_marge_EBITDA
 */
Ratios.prototype['taux_marge_EBITDA'] = undefined;

/**
 * Taux de marge opérationnelle (EBIT) (en %) de l'entreprise.
 * @member {Number} taux_marge_operationnelle
 */
Ratios.prototype['taux_marge_operationnelle'] = undefined;

/**
 * BFR (Besoin en fonds de roulement) de l'entreprise.
 * @member {Number} BFR
 */
Ratios.prototype['BFR'] = undefined;

/**
 * BFR exploitation de l'entreprise.
 * @member {Number} BFR_exploitation
 */
Ratios.prototype['BFR_exploitation'] = undefined;

/**
 * BFR hors exploitation de l'entreprise.
 * @member {Number} BFR_hors_exploitation
 */
Ratios.prototype['BFR_hors_exploitation'] = undefined;

/**
 * BFR (en jours de CA) de l'entreprise.
 * @member {Number} BFR_jours_CA
 */
Ratios.prototype['BFR_jours_CA'] = undefined;

/**
 * BFR exploitation (en jours de CA) de l'entreprise.
 * @member {Number} BFR_exploitation_jours_CA
 */
Ratios.prototype['BFR_exploitation_jours_CA'] = undefined;

/**
 * BFR hors exploitation (en jours de CA) de l'entreprise.
 * @member {Number} BFR_hors_exploitation_jours_CA
 */
Ratios.prototype['BFR_hors_exploitation_jours_CA'] = undefined;

/**
 * Délai de paiement clients (en jours) de l'entreprise.
 * @member {Number} delai_paiement_clients_jours
 */
Ratios.prototype['delai_paiement_clients_jours'] = undefined;

/**
 * Délai de paiement fournisseurs (en jours) de l'entreprise.
 * @member {Number} delai_paiement_fournisseurs_jours
 */
Ratios.prototype['delai_paiement_fournisseurs_jours'] = undefined;

/**
 * Ratio des stocks / CA (en jours) de l'entreprise.
 * @member {Number} ratio_stock_CA_jours
 */
Ratios.prototype['ratio_stock_CA_jours'] = undefined;

/**
 * Capacité d'autofinancement de l'entreprise.
 * @member {Number} capacite_autofinancement
 */
Ratios.prototype['capacite_autofinancement'] = undefined;

/**
 * Capacité d'autofinancement / CA (en %) de l'entreprise.
 * @member {Number} capacite_autofinancement_CA
 */
Ratios.prototype['capacite_autofinancement_CA'] = undefined;

/**
 * Fonds de roulement net global de l'entreprise.
 * @member {Number} fonds_roulement_net_global
 */
Ratios.prototype['fonds_roulement_net_global'] = undefined;

/**
 * Couverture du BFR de l'entreprise.
 * @member {Number} couverture_BFR
 */
Ratios.prototype['couverture_BFR'] = undefined;

/**
 * Trésorerie de l'entreprise.
 * @member {Number} tresorerie
 */
Ratios.prototype['tresorerie'] = undefined;

/**
 * Dettes financières de l'entreprise.
 * @member {Number} dettes_financieres
 */
Ratios.prototype['dettes_financieres'] = undefined;

/**
 * Capacité de remboursement de l'entreprise.
 * @member {Number} capacite_remboursement
 */
Ratios.prototype['capacite_remboursement'] = undefined;

/**
 * Ratio d'endettement (Gearing) de l'entreprise.
 * @member {Number} ratio_endettement
 */
Ratios.prototype['ratio_endettement'] = undefined;

/**
 * Autonomie financière (en %) de l'entreprise.
 * @member {Number} autonomie_financiere
 */
Ratios.prototype['autonomie_financiere'] = undefined;

/**
 * Taux de levier (DFN/EBITDA) de l'entreprise.
 * @member {Number} taux_levier
 */
Ratios.prototype['taux_levier'] = undefined;

/**
 * Etat des dettes à 1 an au plus de l'entreprise.
 * @member {Number} etat_dettes_1_an_au_plus
 */
Ratios.prototype['etat_dettes_1_an_au_plus'] = undefined;

/**
 * Liquidité générale de l'entreprise.
 * @member {Number} liquidite_generale
 */
Ratios.prototype['liquidite_generale'] = undefined;

/**
 * Couverture des dettes de l'entreprise.
 * @member {Number} couverture_dettes
 */
Ratios.prototype['couverture_dettes'] = undefined;

/**
 * Marge nette (en %) de l'entreprise.
 * @member {Number} marge_nette
 */
Ratios.prototype['marge_nette'] = undefined;

/**
 * Rentabilité sur fonds propres (en %) de l'entreprise.
 * @member {Number} rentabilite_fonds_propres
 */
Ratios.prototype['rentabilite_fonds_propres'] = undefined;

/**
 * Rentabilité économique (en %) de l'entreprise.
 * @member {Number} rentabilite_economique
 */
Ratios.prototype['rentabilite_economique'] = undefined;

/**
 * Valeur ajoutée de l'entreprise.
 * @member {Number} valeur_ajoutee
 */
Ratios.prototype['valeur_ajoutee'] = undefined;

/**
 * Valeur ajoutée / CA (en %) de l'entreprise.
 * @member {Number} valeur_ajoutee_CA
 */
Ratios.prototype['valeur_ajoutee_CA'] = undefined;

/**
 * Salaires et charges sociales de l'entreprise.
 * @member {Number} salaires_charges_sociales
 */
Ratios.prototype['salaires_charges_sociales'] = undefined;

/**
 * Salaires / CA (en %) de l'entreprise.
 * @member {Number} salaires_CA
 */
Ratios.prototype['salaires_CA'] = undefined;

/**
 * Impôts et taxes de l'entreprise.
 * @member {Number} impots_taxes
 */
Ratios.prototype['impots_taxes'] = undefined;






export default Ratios;

