/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";

/**
* ComptesAnnuels service.
* @module api/ComptesAnnuelsApi
* @version 2.3.0
*/
export default class ComptesAnnuelsApi {

    /**
    * Constructs a new ComptesAnnuelsApi. 
    * @alias module:api/ComptesAnnuelsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the comptesAnnuels operation.
     * @callback module:api/ComptesAnnuelsApi~comptesAnnuelsCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, {String: [Object]}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Récupère les comptes annuels publiés d'une entreprise.
     * Vous devez fournir le SIREN de l'entreprise pour laquelle vous souhaitez obtenir les comptes annuels.
     * @param {String} apiToken Clé d'utilisation de l'API
     * @param {Object} opts Optional parameters
     * @param {String} opts.siren SIREN de l'entreprise
     * @param {String} opts.annee Année de cloture des comptes souhaités. Il est possible d'indiquer plusieurs années en les séparant par des virgules. Si le paramètre n'est pas fourni, toutes les années disponibles seront retournées.
     * @param {module:api/ComptesAnnuelsApi~comptesAnnuelsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, {String: [Object]}>}
     */
    comptesAnnuels(apiToken, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'apiToken' is set
      if (apiToken === undefined || apiToken === null) {
        throw new Error("Missing the required parameter 'apiToken' when calling comptesAnnuels");
      }

      let pathParams = {
      };
      let queryParams = {
        'api_token': apiToken,
        'siren': opts['siren'],
        'annee': opts['annee']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = {'String': [Object]};
      return this.apiClient.callApi(
        '/entreprise/comptes', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
