/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PappersApi);
  }
}(this, function(expect, PappersApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PappersApi.EntrepriseRecherche();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EntrepriseRecherche', function() {
    it('should create an instance of EntrepriseRecherche', function() {
      // uncomment below and update the code to test EntrepriseRecherche
      //var instane = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be.a(PappersApi.EntrepriseRecherche);
    });

    it('should have the property siren (base name: "siren")', function() {
      // uncomment below and update the code to test the property siren
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property sirenFormate (base name: "siren_formate")', function() {
      // uncomment below and update the code to test the property sirenFormate
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property nomEntreprise (base name: "nom_entreprise")', function() {
      // uncomment below and update the code to test the property nomEntreprise
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property personneMorale (base name: "personne_morale")', function() {
      // uncomment below and update the code to test the property personneMorale
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property denomination (base name: "denomination")', function() {
      // uncomment below and update the code to test the property denomination
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property nom (base name: "nom")', function() {
      // uncomment below and update the code to test the property nom
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property prenom (base name: "prenom")', function() {
      // uncomment below and update the code to test the property prenom
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property sexe (base name: "sexe")', function() {
      // uncomment below and update the code to test the property sexe
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property codeNaf (base name: "code_naf")', function() {
      // uncomment below and update the code to test the property codeNaf
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property libelleCodeNaf (base name: "libelle_code_naf")', function() {
      // uncomment below and update the code to test the property libelleCodeNaf
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property domaineActivite (base name: "domaine_activite")', function() {
      // uncomment below and update the code to test the property domaineActivite
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property conventionsCollectives (base name: "conventions_collectives")', function() {
      // uncomment below and update the code to test the property conventionsCollectives
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property dateCreation (base name: "date_creation")', function() {
      // uncomment below and update the code to test the property dateCreation
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property dateCreationFormate (base name: "date_creation_formate")', function() {
      // uncomment below and update the code to test the property dateCreationFormate
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property entrepriseCessee (base name: "entreprise_cessee")', function() {
      // uncomment below and update the code to test the property entrepriseCessee
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property dateCessation (base name: "date_cessation")', function() {
      // uncomment below and update the code to test the property dateCessation
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property entrepriseEmployeuse (base name: "entreprise_employeuse")', function() {
      // uncomment below and update the code to test the property entrepriseEmployeuse
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property categorieJuridique (base name: "categorie_juridique")', function() {
      // uncomment below and update the code to test the property categorieJuridique
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property formeJuridique (base name: "forme_juridique")', function() {
      // uncomment below and update the code to test the property formeJuridique
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property effectif (base name: "effectif")', function() {
      // uncomment below and update the code to test the property effectif
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property effectifMin (base name: "effectif_min")', function() {
      // uncomment below and update the code to test the property effectifMin
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property effectifMax (base name: "effectif_max")', function() {
      // uncomment below and update the code to test the property effectifMax
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property trancheEffectif (base name: "tranche_effectif")', function() {
      // uncomment below and update the code to test the property trancheEffectif
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property anneeEffectif (base name: "annee_effectif")', function() {
      // uncomment below and update the code to test the property anneeEffectif
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property capital (base name: "capital")', function() {
      // uncomment below and update the code to test the property capital
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property statutRcs (base name: "statut_rcs")', function() {
      // uncomment below and update the code to test the property statutRcs
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property siege (base name: "siege")', function() {
      // uncomment below and update the code to test the property siege
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property villes (base name: "villes")', function() {
      // uncomment below and update the code to test the property villes
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property chiffreAffaires (base name: "chiffre_affaires")', function() {
      // uncomment below and update the code to test the property chiffreAffaires
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property resultat (base name: "resultat")', function() {
      // uncomment below and update the code to test the property resultat
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property effectifsFinances (base name: "effectifs_finances")', function() {
      // uncomment below and update the code to test the property effectifsFinances
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

    it('should have the property anneeFinances (base name: "annee_finances")', function() {
      // uncomment below and update the code to test the property anneeFinances
      //var instance = new PappersApi.EntrepriseRecherche();
      //expect(instance).to.be();
    });

  });

}));
