/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PappersApi);
  }
}(this, function(expect, PappersApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PappersApi.EtablissementRecherche();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EtablissementRecherche', function() {
    it('should create an instance of EtablissementRecherche', function() {
      // uncomment below and update the code to test EtablissementRecherche
      //var instane = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be.a(PappersApi.EtablissementRecherche);
    });

    it('should have the property siret (base name: "siret")', function() {
      // uncomment below and update the code to test the property siret
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property siretFormate (base name: "siret_formate")', function() {
      // uncomment below and update the code to test the property siretFormate
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property nic (base name: "nic")', function() {
      // uncomment below and update the code to test the property nic
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property numeroVoie (base name: "numero_voie")', function() {
      // uncomment below and update the code to test the property numeroVoie
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property indiceRepetition (base name: "indice_repetition")', function() {
      // uncomment below and update the code to test the property indiceRepetition
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property typeVoie (base name: "type_voie")', function() {
      // uncomment below and update the code to test the property typeVoie
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property libelleVoie (base name: "libelle_voie")', function() {
      // uncomment below and update the code to test the property libelleVoie
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property complementAdresse (base name: "complement_adresse")', function() {
      // uncomment below and update the code to test the property complementAdresse
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property adresseLigne1 (base name: "adresse_ligne_1")', function() {
      // uncomment below and update the code to test the property adresseLigne1
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property adresseLigne2 (base name: "adresse_ligne_2")', function() {
      // uncomment below and update the code to test the property adresseLigne2
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property codePostal (base name: "code_postal")', function() {
      // uncomment below and update the code to test the property codePostal
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property ville (base name: "ville")', function() {
      // uncomment below and update the code to test the property ville
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instance = new PappersApi.EtablissementRecherche();
      //expect(instance).to.be();
    });

  });

}));
