/**
 * Pappers API
 * L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Beneficiaire from './model/Beneficiaire';
import Bodacc from './model/Bodacc';
import BodaccCreation from './model/BodaccCreation';
import BodaccCreationAllOf from './model/BodaccCreationAllOf';
import BodaccDepotDesComptes from './model/BodaccDepotDesComptes';
import BodaccDepotDesComptesAllOf from './model/BodaccDepotDesComptesAllOf';
import BodaccImmatriculation from './model/BodaccImmatriculation';
import BodaccImmatriculationAllOf from './model/BodaccImmatriculationAllOf';
import BodaccModification from './model/BodaccModification';
import BodaccModificationAllOf from './model/BodaccModificationAllOf';
import BodaccProcedureCollective from './model/BodaccProcedureCollective';
import BodaccProcedureCollectiveAllOf from './model/BodaccProcedureCollectiveAllOf';
import BodaccRadiation from './model/BodaccRadiation';
import BodaccVente from './model/BodaccVente';
import BodaccVenteAllOf from './model/BodaccVenteAllOf';
import Document from './model/Document';
import DocumentActe from './model/DocumentActe';
import DocumentActeAllOf from './model/DocumentActeAllOf';
import DocumentActeAllOfTitres from './model/DocumentActeAllOfTitres';
import DocumentComptes from './model/DocumentComptes';
import DocumentComptesAllOf from './model/DocumentComptesAllOf';
import EntrepriseBase from './model/EntrepriseBase';
import EntrepriseBaseConventionsCollectives from './model/EntrepriseBaseConventionsCollectives';
import EntrepriseFiche from './model/EntrepriseFiche';
import EntrepriseFicheAllOf from './model/EntrepriseFicheAllOf';
import EntrepriseFicheAllOfActes from './model/EntrepriseFicheAllOfActes';
import EntrepriseFicheAllOfBeneficiairesEffectifs from './model/EntrepriseFicheAllOfBeneficiairesEffectifs';
import EntrepriseFicheAllOfClasses from './model/EntrepriseFicheAllOfClasses';
import EntrepriseFicheAllOfComptes from './model/EntrepriseFicheAllOfComptes';
import EntrepriseFicheAllOfDepotsActes from './model/EntrepriseFicheAllOfDepotsActes';
import EntrepriseFicheAllOfDerniersStatuts from './model/EntrepriseFicheAllOfDerniersStatuts';
import EntrepriseFicheAllOfDetailsPartsDirectes from './model/EntrepriseFicheAllOfDetailsPartsDirectes';
import EntrepriseFicheAllOfDetailsPartsIndirectes from './model/EntrepriseFicheAllOfDetailsPartsIndirectes';
import EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnIndivision from './model/EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnIndivision';
import EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnPersonneMorale from './model/EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnPersonneMorale';
import EntrepriseFicheAllOfDetailsPartsVocationTitulaire from './model/EntrepriseFicheAllOfDetailsPartsVocationTitulaire';
import EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes from './model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes';
import EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes from './model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes';
import EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnIndivision from './model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnIndivision';
import EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnPersonneMorale from './model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnPersonneMorale';
import EntrepriseFicheAllOfDetailsSocieteDeGestion from './model/EntrepriseFicheAllOfDetailsSocieteDeGestion';
import EntrepriseFicheAllOfDetailsVotesDirects from './model/EntrepriseFicheAllOfDetailsVotesDirects';
import EntrepriseFicheAllOfDetailsVotesIndirects from './model/EntrepriseFicheAllOfDetailsVotesIndirects';
import EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnIndivision from './model/EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnIndivision';
import EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnPersonneMorale from './model/EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnPersonneMorale';
import EntrepriseFicheAllOfEvenements from './model/EntrepriseFicheAllOfEvenements';
import EntrepriseFicheAllOfExtraitImmatriculation from './model/EntrepriseFicheAllOfExtraitImmatriculation';
import EntrepriseFicheAllOfMarques from './model/EntrepriseFicheAllOfMarques';
import EntrepriseFicheAllOfProceduresCollectives from './model/EntrepriseFicheAllOfProceduresCollectives';
import EntrepriseFicheAllOfRnm from './model/EntrepriseFicheAllOfRnm';
import EntrepriseRecherche from './model/EntrepriseRecherche';
import EntrepriseRechercheAllOf from './model/EntrepriseRechercheAllOf';
import EtablissementFiche from './model/EtablissementFiche';
import EtablissementFicheDomiciliation from './model/EtablissementFicheDomiciliation';
import EtablissementRecherche from './model/EtablissementRecherche';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import PersonneMarque from './model/PersonneMarque';
import Publication from './model/Publication';
import Ratios from './model/Ratios';
import Representant from './model/Representant';
import RepresentantRecherche from './model/RepresentantRecherche';
import RepresentantRechercheAllOf from './model/RepresentantRechercheAllOf';
import ComptesAnnuelsApi from './api/ComptesAnnuelsApi';
import DocumentsApi from './api/DocumentsApi';
import FicheEntrepriseApi from './api/FicheEntrepriseApi';
import RechercheApi from './api/RechercheApi';
import SuggestionsAutocompleteApi from './api/SuggestionsAutocompleteApi';


/**
* LAPI_de_Pappers_vous_permet_de_rcuprer_des_informations_et_documents_sur_les_entreprises_franaises__partir_de_leur_numro_SIREN_ou_SIRET_Vous_devez_indiquer_votre_cl_dAPI_dans_les_requtes_en_utilisant_le_paramtre_api_token_LURL_daccs__lAPI_est_https__api_pappers_fr_v2_Lien_vers_la_documentation_de_la_V1__https__www_pappers_fr_api_documentation_v1Lhistorique_des_modifications__changelog_est_accessible__lurl_suivante__https__www_pappers_fr_api_changelog.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PappersApi = require('index'); // See note below*.
* var xxxSvc = new PappersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PappersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PappersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PappersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.3.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Beneficiaire model constructor.
     * @property {module:model/Beneficiaire}
     */
    Beneficiaire,

    /**
     * The Bodacc model constructor.
     * @property {module:model/Bodacc}
     */
    Bodacc,

    /**
     * The BodaccCreation model constructor.
     * @property {module:model/BodaccCreation}
     */
    BodaccCreation,

    /**
     * The BodaccCreationAllOf model constructor.
     * @property {module:model/BodaccCreationAllOf}
     */
    BodaccCreationAllOf,

    /**
     * The BodaccDepotDesComptes model constructor.
     * @property {module:model/BodaccDepotDesComptes}
     */
    BodaccDepotDesComptes,

    /**
     * The BodaccDepotDesComptesAllOf model constructor.
     * @property {module:model/BodaccDepotDesComptesAllOf}
     */
    BodaccDepotDesComptesAllOf,

    /**
     * The BodaccImmatriculation model constructor.
     * @property {module:model/BodaccImmatriculation}
     */
    BodaccImmatriculation,

    /**
     * The BodaccImmatriculationAllOf model constructor.
     * @property {module:model/BodaccImmatriculationAllOf}
     */
    BodaccImmatriculationAllOf,

    /**
     * The BodaccModification model constructor.
     * @property {module:model/BodaccModification}
     */
    BodaccModification,

    /**
     * The BodaccModificationAllOf model constructor.
     * @property {module:model/BodaccModificationAllOf}
     */
    BodaccModificationAllOf,

    /**
     * The BodaccProcedureCollective model constructor.
     * @property {module:model/BodaccProcedureCollective}
     */
    BodaccProcedureCollective,

    /**
     * The BodaccProcedureCollectiveAllOf model constructor.
     * @property {module:model/BodaccProcedureCollectiveAllOf}
     */
    BodaccProcedureCollectiveAllOf,

    /**
     * The BodaccRadiation model constructor.
     * @property {module:model/BodaccRadiation}
     */
    BodaccRadiation,

    /**
     * The BodaccVente model constructor.
     * @property {module:model/BodaccVente}
     */
    BodaccVente,

    /**
     * The BodaccVenteAllOf model constructor.
     * @property {module:model/BodaccVenteAllOf}
     */
    BodaccVenteAllOf,

    /**
     * The Document model constructor.
     * @property {module:model/Document}
     */
    Document,

    /**
     * The DocumentActe model constructor.
     * @property {module:model/DocumentActe}
     */
    DocumentActe,

    /**
     * The DocumentActeAllOf model constructor.
     * @property {module:model/DocumentActeAllOf}
     */
    DocumentActeAllOf,

    /**
     * The DocumentActeAllOfTitres model constructor.
     * @property {module:model/DocumentActeAllOfTitres}
     */
    DocumentActeAllOfTitres,

    /**
     * The DocumentComptes model constructor.
     * @property {module:model/DocumentComptes}
     */
    DocumentComptes,

    /**
     * The DocumentComptesAllOf model constructor.
     * @property {module:model/DocumentComptesAllOf}
     */
    DocumentComptesAllOf,

    /**
     * The EntrepriseBase model constructor.
     * @property {module:model/EntrepriseBase}
     */
    EntrepriseBase,

    /**
     * The EntrepriseBaseConventionsCollectives model constructor.
     * @property {module:model/EntrepriseBaseConventionsCollectives}
     */
    EntrepriseBaseConventionsCollectives,

    /**
     * The EntrepriseFiche model constructor.
     * @property {module:model/EntrepriseFiche}
     */
    EntrepriseFiche,

    /**
     * The EntrepriseFicheAllOf model constructor.
     * @property {module:model/EntrepriseFicheAllOf}
     */
    EntrepriseFicheAllOf,

    /**
     * The EntrepriseFicheAllOfActes model constructor.
     * @property {module:model/EntrepriseFicheAllOfActes}
     */
    EntrepriseFicheAllOfActes,

    /**
     * The EntrepriseFicheAllOfBeneficiairesEffectifs model constructor.
     * @property {module:model/EntrepriseFicheAllOfBeneficiairesEffectifs}
     */
    EntrepriseFicheAllOfBeneficiairesEffectifs,

    /**
     * The EntrepriseFicheAllOfClasses model constructor.
     * @property {module:model/EntrepriseFicheAllOfClasses}
     */
    EntrepriseFicheAllOfClasses,

    /**
     * The EntrepriseFicheAllOfComptes model constructor.
     * @property {module:model/EntrepriseFicheAllOfComptes}
     */
    EntrepriseFicheAllOfComptes,

    /**
     * The EntrepriseFicheAllOfDepotsActes model constructor.
     * @property {module:model/EntrepriseFicheAllOfDepotsActes}
     */
    EntrepriseFicheAllOfDepotsActes,

    /**
     * The EntrepriseFicheAllOfDerniersStatuts model constructor.
     * @property {module:model/EntrepriseFicheAllOfDerniersStatuts}
     */
    EntrepriseFicheAllOfDerniersStatuts,

    /**
     * The EntrepriseFicheAllOfDetailsPartsDirectes model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsDirectes}
     */
    EntrepriseFicheAllOfDetailsPartsDirectes,

    /**
     * The EntrepriseFicheAllOfDetailsPartsIndirectes model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsIndirectes}
     */
    EntrepriseFicheAllOfDetailsPartsIndirectes,

    /**
     * The EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnIndivision model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnIndivision}
     */
    EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnIndivision,

    /**
     * The EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnPersonneMorale model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnPersonneMorale}
     */
    EntrepriseFicheAllOfDetailsPartsIndirectesDetailsEnPersonneMorale,

    /**
     * The EntrepriseFicheAllOfDetailsPartsVocationTitulaire model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaire}
     */
    EntrepriseFicheAllOfDetailsPartsVocationTitulaire,

    /**
     * The EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes}
     */
    EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsDirectes,

    /**
     * The EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes}
     */
    EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectes,

    /**
     * The EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnIndivision model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnIndivision}
     */
    EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnIndivision,

    /**
     * The EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnPersonneMorale model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnPersonneMorale}
     */
    EntrepriseFicheAllOfDetailsPartsVocationTitulaireDetailsIndirectesDetailsEnPersonneMorale,

    /**
     * The EntrepriseFicheAllOfDetailsSocieteDeGestion model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsSocieteDeGestion}
     */
    EntrepriseFicheAllOfDetailsSocieteDeGestion,

    /**
     * The EntrepriseFicheAllOfDetailsVotesDirects model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsVotesDirects}
     */
    EntrepriseFicheAllOfDetailsVotesDirects,

    /**
     * The EntrepriseFicheAllOfDetailsVotesIndirects model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsVotesIndirects}
     */
    EntrepriseFicheAllOfDetailsVotesIndirects,

    /**
     * The EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnIndivision model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnIndivision}
     */
    EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnIndivision,

    /**
     * The EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnPersonneMorale model constructor.
     * @property {module:model/EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnPersonneMorale}
     */
    EntrepriseFicheAllOfDetailsVotesIndirectsDetailsEnPersonneMorale,

    /**
     * The EntrepriseFicheAllOfEvenements model constructor.
     * @property {module:model/EntrepriseFicheAllOfEvenements}
     */
    EntrepriseFicheAllOfEvenements,

    /**
     * The EntrepriseFicheAllOfExtraitImmatriculation model constructor.
     * @property {module:model/EntrepriseFicheAllOfExtraitImmatriculation}
     */
    EntrepriseFicheAllOfExtraitImmatriculation,

    /**
     * The EntrepriseFicheAllOfMarques model constructor.
     * @property {module:model/EntrepriseFicheAllOfMarques}
     */
    EntrepriseFicheAllOfMarques,

    /**
     * The EntrepriseFicheAllOfProceduresCollectives model constructor.
     * @property {module:model/EntrepriseFicheAllOfProceduresCollectives}
     */
    EntrepriseFicheAllOfProceduresCollectives,

    /**
     * The EntrepriseFicheAllOfRnm model constructor.
     * @property {module:model/EntrepriseFicheAllOfRnm}
     */
    EntrepriseFicheAllOfRnm,

    /**
     * The EntrepriseRecherche model constructor.
     * @property {module:model/EntrepriseRecherche}
     */
    EntrepriseRecherche,

    /**
     * The EntrepriseRechercheAllOf model constructor.
     * @property {module:model/EntrepriseRechercheAllOf}
     */
    EntrepriseRechercheAllOf,

    /**
     * The EtablissementFiche model constructor.
     * @property {module:model/EtablissementFiche}
     */
    EtablissementFiche,

    /**
     * The EtablissementFicheDomiciliation model constructor.
     * @property {module:model/EtablissementFicheDomiciliation}
     */
    EtablissementFicheDomiciliation,

    /**
     * The EtablissementRecherche model constructor.
     * @property {module:model/EtablissementRecherche}
     */
    EtablissementRecherche,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The PersonneMarque model constructor.
     * @property {module:model/PersonneMarque}
     */
    PersonneMarque,

    /**
     * The Publication model constructor.
     * @property {module:model/Publication}
     */
    Publication,

    /**
     * The Ratios model constructor.
     * @property {module:model/Ratios}
     */
    Ratios,

    /**
     * The Representant model constructor.
     * @property {module:model/Representant}
     */
    Representant,

    /**
     * The RepresentantRecherche model constructor.
     * @property {module:model/RepresentantRecherche}
     */
    RepresentantRecherche,

    /**
     * The RepresentantRechercheAllOf model constructor.
     * @property {module:model/RepresentantRechercheAllOf}
     */
    RepresentantRechercheAllOf,

    /**
    * The ComptesAnnuelsApi service constructor.
    * @property {module:api/ComptesAnnuelsApi}
    */
    ComptesAnnuelsApi,

    /**
    * The DocumentsApi service constructor.
    * @property {module:api/DocumentsApi}
    */
    DocumentsApi,

    /**
    * The FicheEntrepriseApi service constructor.
    * @property {module:api/FicheEntrepriseApi}
    */
    FicheEntrepriseApi,

    /**
    * The RechercheApi service constructor.
    * @property {module:api/RechercheApi}
    */
    RechercheApi,

    /**
    * The SuggestionsAutocompleteApi service constructor.
    * @property {module:api/SuggestionsAutocompleteApi}
    */
    SuggestionsAutocompleteApi
};
